# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Miranda Benzies
email: mfgillett@gmail.com
tel: 07840046363
social:
  facebook: https://www.facebook.com/mirandamantlepiece
  twitter: https://twitter.com/wizconda
description: >- # this means to ignore newlines until "baseurl:"
  This is a website to commemorate Miranda Benzies.
baseurl: "/oscarbob.github.io" # the subpath of your site, e.g. /blog
url: "https://oscarbob.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  oscarbob

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed
# sass:
#   sass_dir: _sass
#   style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
